---
galaxy_info:
  description: Remove Keycloak runtime resources with guarded destructive flags
  company: Lightning IT
  author: Dirk Egert, René Osorio
  license: MIT
  min_ansible_version: '2.18'
  role_name: keycloak_destroy
  namespace: default
  galaxy_tags: []
dependencies: []
