---
collections:
  - name: https://github.com/ansible/ansible.platform.git
    type: git
    version: "2.5.20250702"
  - name: ansible.posix
    version: "2.1.0"
  - name: ansible.hub
    version: "1.0.4"
  - name: ansible.eda
    version: "2.11.0"
  - name: community.general
    version: "11.4.4"
  - name: community.crypto
    version: "2.26.7"
  - name: community.hashi_vault
    version: "7.1.0"
  - name: community.vmware
    version: "6.2.0"
  - name: containers.podman
    version: "1.19.0"
  - name: infra.aap_utilities
    version: "2.7.0"
  - name: infra.aap_configuration
    version: "3.9.1"
  - name: infra.aap_configuration_extended
    version: "1.1.1"
  - name: infra.controller_configuration
    version: "3.1.2"
  - name: infra.ee_utilities
    version: "4.0.4"
