---
dependency:
  name: galaxy

driver:
  name: delegated
  options:
    managed: false

platforms:
  - name: localhost

provisioner:
  name: ansible
  lint: |
    yamllint .
    ansible-lint
  env:
    ANSIBLE_COLLECTIONS_PATHS: >-
      {{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}
  playbooks:
    converge: converge.yml
    destroy: destroy.yml
    verify: verify.yml

verifier:
  name: ansible
