---
galaxy_info:
  role_name: keycloak_deploy
  namespace: lit
  author: Lightning IT
  description: Deploy Keycloak with PostgreSQL in a Podman pod.
  company: Lightning IT
  license: GPL-3.0-only
  min_ansible_version: "2.18"
  platforms:
    - name: EL
      versions:
        - "9"
  galaxy_tags:
    - modulix
    - keycloak
    - podman
    - automation
    - devops

dependencies: []
