---
galaxy_info:
  description: Run day-2 Keycloak operational actions
  company: Lightning IT
  author: Dirk Egert, René Osorio
  license: MIT
  min_ansible_version: '2.18'
  role_name: keycloak_ops
  namespace: default
  galaxy_tags: []
dependencies: []
