---
galaxy_info:
  role_name: aap_host_prepare
  namespace: lit
  author: René Osorio
  description: AAP-owned host preparation after the OS baseline.
  company: Lightning IT
  license: MIT
  min_ansible_version: "2.18"
  platforms:
    - name: EL
      versions:
        - "all"
  galaxy_tags:
    - aap
    - automation

dependencies: []
