---
self-hosted-runner:
  labels:
    - incus
    - keycloak-test
paths:
  .github/workflows/collection-publish.yml:
    ignore:
      - 'unexpected key "queue" for "concurrency" section'
  .github/workflows/release-back-sync.yml:
    ignore:
      - 'unexpected key "queue" for "concurrency" section'
  .github/workflows/release-prepare.yml:
    ignore:
      - 'unexpected key "queue" for "concurrency" section'
