---
galaxy_info:
  role_name: aap_config
  namespace: lit
  author: René Osorio
  description: Manage AAP configuration file content.
  company: Lightning IT
  license: GPL-3.0-only
  min_ansible_version: "2.18"
  platforms:
    - name: EL
      versions:
        - "all"
  galaxy_tags:
    - modulix
    - aap
    - automation
    - configuration

dependencies: []
