namespace: lit
name: supplementary
version: 1.9.0
readme: README.md
description: Supplementary Ansible collection for ModuLix, providing configuration
  and integration roles for platform services and Terraform-backed workflows.
repository: https://github.com/lightning-it/ansible-collection-supplementary
authors:
- Lightning IT
license:
- GPL-3.0-only
tags:
- modulix
- keycloak
- terraform
- security
- automation
dependencies:
  ansible.posix: '*'
  community.general: '*'
  community.vmware: '*'
build_ignore:
- node_modules
- vagrant
- .git
- .github
- .gitignore
- .molecule
- ansible_collections
- infra
- '*.terraform*'
- '*.tar.gz'
