---
namespace: lit
name: supplementary
version: 1.14.0
  ansible.posix: '*'
  community.general: '*'
  community.hashi_vault: '*'
  community.vmware: '*'
build_ignore:
  - node_modules
  - vagrant
  - .git
  - .github
  - .gitignore
  - .molecule
  - .ansible
  - ansible_collections
  - infra
  - '*.terraform*'
  - '*.tar.gz'
