---
dependency:
  name: galaxy

driver:
  name: default
  options:
    managed: false

platforms:
  - name: localhost
    address: localhost
    connection_options:
      ansible_connection: local

provisioner:
  name: ansible
  lint: |
    yamllint .
    ansible-lint
  env:
    ANSIBLE_COLLECTIONS_PATHS: >-
      {{ lookup('env','ANSIBLE_COLLECTIONS_PATH') }}:
      {{ molecule_project_directory }}/collections-dev:
      {{ molecule_project_directory }}/collections
    ANSIBLE_ROLES_PATH: "../../roles"
  inventory:
    host_vars:
      localhost:
        ansible_connection: local
        cloudflared_tunnel_token: "dummy-token-for-molecule-tests-1234567890"
        cloudflared_manage_repo: false
        cloudflared_install: false
        cloudflared_manage_service: false
        cloudflared_show_status: false
  playbooks:
    converge: converge.yml
    destroy: destroy.yml
    verify: verify.yml

verifier:
  name: ansible
