---
galaxy_info:
  role_name: dhcp_deploy
  namespace: lit
  author: Lightning IT
  description: Deploy DHCP as a rootful Podman kube-play pod.
  company: Lightning IT
  license: MIT
  min_ansible_version: "2.18"
  platforms:
    - name: EL
      versions:
        - "9"
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - modulix
    - dhcp
    - podman
    - networking
    - automation

dependencies: []
