---
- name: Ensure minio_foundational variables are valid
  ansible.builtin.assert:
    that:
      - minio_foundational_generate_root_credentials is boolean
      - minio_foundational_store_root_credentials is boolean
      - minio_foundational_vault_use_token is boolean
      - minio_foundational_vault_auth_ok is boolean
  changed_when: false
  tags: always
