---
samba_deploy_packages:
  - samba
  - smbclient
samba_deploy_install_packages: true
samba_deploy_manage_systemd: true
samba_deploy_skip_runtime: false
samba_deploy_skip_deploy: false

samba_deploy_workgroup: "WORKGROUP"
samba_deploy_server_string: "Samba Server"
samba_deploy_security: "user"
samba_deploy_map_to_guest: "Bad User"
samba_deploy_config_path: "/etc/samba/smb.conf"
samba_deploy_share_name: "public"
samba_deploy_share_path: "/srv/samba/public"
samba_deploy_share_comment: "Public Samba Share"
samba_deploy_share_guest_ok: true
samba_deploy_share_read_only: false
samba_deploy_share_browseable: true
samba_deploy_share_create_mask: "0664"
samba_deploy_share_directory_mask: "0775"
samba_deploy_share_owner: "nobody"
samba_deploy_share_group: "nogroup"
samba_deploy_share_mode: "0775"
samba_deploy_extra_global_options: {}
samba_deploy_extra_share_options: {}
samba_deploy_smbd_path: "/usr/sbin/smbd"
samba_deploy_nmbd_path: "/usr/sbin/nmbd"
samba_deploy_smbd_service: "smbd"
samba_deploy_nmbd_service: "nmbd"
