---
dependency:
  name: shell
  command: ":"

driver:
  name: default
  options:
    managed: false

platforms:
  - name: localhost
    address: localhost
    connection_options:
      ansible_connection: local

provisioner:
  name: ansible
  lint: |
    yamllint .
    ansible-lint
  env:
    ANSIBLE_COLLECTIONS_PATH: "/tmp/wunder/collections:../../collections"
    ANSIBLE_ROLES_PATH: "roles:../../roles"
  inventory:
    host_vars:
      localhost:
        ansible_connection: local
  playbooks:
    converge: converge.yml
    destroy: destroy.yml
    verify: verify.yml

verifier:
  name: ansible
