---
galaxy_info:
  role_name: loki_deploy
  namespace: lit
  author: Lightning IT
  description: Deploy Loki with Podman Quadlet.
  company: Lightning IT
  license: MIT
  min_ansible_version: "2.18"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
    - name: EL
      versions:
        - "9"
  galaxy_tags:
    - modulix
    - loki
    - logging
    - podman
    - quadlet

dependencies: []
