---
galaxy_info:
  description: Apply Keycloak runtime configuration inputs
  company: Lightning IT
  author: Dirk Egert, René Osorio
  license: MIT
  min_ansible_version: '2.18'
  role_name: keycloak_config
  namespace: default
  galaxy_tags: []
dependencies: []
