---
- name: Import coredns_deploy prechecks
  ansible.builtin.import_role:
    name: coredns_deploy
    tasks_from: assert
  tags: always

- name: Ensure coredns_ops variables are valid
  ansible.builtin.assert:
    that:
      - coredns_ops_action in ['none', 'restart', 'reload', 'status', 'upgrade']
      - coredns_ops_target_image is string
      - coredns_deploy_systemd_unit_name | default('', true) | trim | length > 0
      - coredns_deploy_pod_name | default('', true) | trim | length > 0
      - coredns_deploy_container_name | default('', true) | trim | length > 0
    fail_msg: "coredns_ops variables are missing or invalid."
    quiet: true
  tags: always
