---
# CaC taskset: Configure Controller Credential Types.
- name: Configure Controller Credential Types
  block:
    - name: Run role infra.aap_configuration.dispatch
      ansible.builtin.include_role:
        name: infra.aap_configuration.dispatch
      vars:
        aap_configuration_dispatcher_roles:
          - role: controller_credential_types
            var: controller_credential_types
            tags: controller_credential_types
      tags:
        - controller_credential_types
