---
# CaC taskset: Configure Gateway Organizations via AAP CaC role task set.
- name: Configure Gateway Organizations via AAP CaC role task set
  tags:
    - organizations
  block:
    - name: Set organizations for gateway organization taskset
      ansible.builtin.set_fact:
        aap_organizations: "{{ aap_cac_controller_organizations }}"
      changed_when: false

    - name: Configure Gateway Organizations  # noqa var-naming[no-role-prefix]
      ansible.builtin.include_role:
        name: infra.aap_configuration.dispatch
      vars:
        aap_configuration_dispatcher_roles:
          - role: gateway_organizations
            var: aap_organizations
            tags: organizations
