---
# CaC taskset: Configure Controller credentials.
- name: Configure Controller credentials
  block:
    - name: Create Automation Hub token
      ansible.hub.ah_token:
        ah_host: '{{ inventory_hostname }}'
        ah_username: '{{ aap_username }}'
        ah_password: '{{ aap_password }}'
        validate_certs: '{{ aap_validate_certs }}'
        state: present
      delegate_to: localhost
      register: __t_ah_token

    - name: Run role infra.aap_configuration.dispatch
      ansible.builtin.include_role:
        name: infra.aap_configuration.dispatch
      vars:
        aap_configuration_dispatcher_roles:
          - role: controller_credentials
            var: controller_credentials
            tags: controller_credentials
      tags:
        - controller_credentials
