---
# CaC taskset: Configure Controller Labels.
- name: Configure Controller Labels
  block:
    - name: Run role infra.aap_configuration.dispatch  # noqa var-naming[no-role-prefix]
      ansible.builtin.include_role:
        name: infra.aap_configuration.dispatch
      vars:
        controller_hostname: "{{ aap_cac_gateway_hostname }}"
        controller_validate_certs: "{{ aap_cac_gateway_validate_certs | bool }}"
        aap_password: "{{ aap_cac_controller_password_effective }}"
        aap_token: "{{ aap_cac_auth_token | default(omit, true) }}"
        aap_configuration_dispatcher_roles:
          - role: controller_labels
            var: controller_labels
            tags: labels
      tags:
        - labels
