---
# CaC taskset: Optional execution of infra.controller_configuration inventory/runtime roles.
- name: Execute optional infra.controller_configuration inventory/runtime roles
  when: aap_cac_controller_configuration_inventory_runtime_roles | length > 0
  vars:
    __aap_cac_allowed_controller_configuration_inventory_runtime_roles:
      - bulk_host_create
      - groups
      - hosts
      - instances
  block:
    - name: Validate selected infra.controller_configuration inventory/runtime roles
      ansible.builtin.assert:
        that:
          - aap_cac_controller_configuration_inventory_runtime_roles is sequence
          - >
            (aap_cac_controller_configuration_inventory_runtime_roles
            | difference(__aap_cac_allowed_controller_configuration_inventory_runtime_roles))
            | length == 0
        fail_msg: >-
          Invalid aap_cac_controller_configuration_inventory_runtime_roles.
          Allowed values:
          {{ __aap_cac_allowed_controller_configuration_inventory_runtime_roles | join(', ') }}

    - name: Include infra.controller_configuration inventory/runtime roles
      ansible.builtin.include_role:
        name: "infra.controller_configuration.{{ item }}"
      loop: "{{ aap_cac_controller_configuration_inventory_runtime_roles }}"
      loop_control:
        label: "{{ item }}"
