---
# CaC taskset: Assign Galaxy Credentials to Gateway Organizations.
- name: Assign Galaxy Credentials to Gateway Organizations
  vars:
    assign_galaxy_credentials_to_org: true
  block:
    - name: Run role infra.aap_configuration.dispatch  # noqa var-naming[no-role-prefix]
      ansible.builtin.include_role:
        name: infra.aap_configuration.dispatch
      vars:
        aap_configuration_dispatcher_roles:
          - role: gateway_organizations
            var: controller_organizations
            tags: organizations
            assign_galaxy_credentials_to_org: true
      tags:
        - organizations
