---
# CaC taskset: Configure Controller settings.
- name: Configure Controller settings
  block:
    - name: Run role infra.aap_configuration.dispatch  # noqa var-naming[no-role-prefix]
      ansible.builtin.include_role:
        name: infra.aap_configuration.dispatch
      vars:
        aap_configuration_dispatcher_roles:
          - role: controller_settings
            var: controller_settings
            tags: settings
      tags:
        - settings
