---
# CaC taskset: Configure Private Automation Hub collection remotes.
- name: Configure Private Automation Hub collection remotes
  tags:
    - hub_collection_remote
    - hub_collection_remotes
  block:
    - name: Set Hub collection remotes
      ansible.builtin.set_fact:
        hub_collection_remotes: "{{ aap_cac_hub_collection_remotes }}"
      changed_when: false

    - name: Run role infra.aap_configuration.hub_collection_remote  # noqa var-naming[no-role-prefix]
      ansible.builtin.include_role:
        name: infra.aap_configuration.hub_collection_remote
      vars:
        aap_password: "{{ aap_cac_hub_password_effective }}"
        aap_token: "{{ aap_cac_auth_token | default(omit, true) }}"
      when: aap_cac_hub_collection_remotes | length > 0
