---
# CaC taskset: Configure Controller settings.
- name: Configure Controller settings
  block:
    - name: Wait for controller readiness
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/wait_for_controller_readiness.yml"

    - name: Run role infra.aap_configuration.dispatch  # noqa var-naming[no-role-prefix]
      ansible.builtin.include_role:
        name: infra.aap_configuration.dispatch
      vars:
        aap_password: >-
          {{
            aap_controller_admin_password_input
            | default(aap_gateway_admin_password_input, true)
            | default('', true)
            | string
            | trim
          }}
        aap_token: ""
        aap_configuration_dispatcher_roles:
          - role: controller_settings
            var: controller_settings
            tags: settings
      tags:
        - settings
