---
# CaC taskset: Configure Controller credentials.
- name: Configure Controller credentials
  block:
    - name: Run role infra.aap_configuration.dispatch  # noqa var-naming[no-role-prefix]
      ansible.builtin.include_role:
        name: infra.aap_configuration.dispatch
      vars:
        aap_configuration_dispatcher_roles:
          - role: controller_credentials
            var: controller_credentials
            tags: controller_credentials
      tags:
        - controller_credentials
