---
# CaC taskset: Configure Private Automation Hub collection remotes.
- name: Configure Private Automation Hub collection remotes
  tags:
    - hub_collection_remote
    - hub_collection_remotes
  block:
    - name: Set Hub collection remotes
      ansible.builtin.set_fact:
        hub_collection_remotes: "{{ aap_cac_hub_collection_remotes }}"
      changed_when: false

    - name: Run role infra.aap_configuration.hub_collection_remote  # noqa var-naming[no-role-prefix]
      ansible.builtin.include_role:
        name: infra.aap_configuration.hub_collection_remote
      vars:
        aap_password: >-
          {{
            aap_hub_admin_password_input
            | default(aap_gateway_admin_password_input, true)
            | default('', true)
            | string
            | trim
          }}
        aap_token: ""
      when: aap_cac_hub_collection_remotes | length > 0
