---
# CaC taskset: Configure Private Automation Hub group roles.
- name: Configure Private Automation Hub group roles
  block:
    - name: Set Hub group roles
      ansible.builtin.set_fact:
        hub_group_roles: "{{ aap_cac_hub_group_roles }}"
      changed_when: false

    - name: Run role infra.aap_configuration.hub_group_roles
      ansible.builtin.include_role:
        name: infra.aap_configuration.hub_group_roles
      when: aap_cac_hub_group_roles | length > 0
