---
# CaC taskset: Synchronize Private Automation Hub repositories.
- name: Synchronize Private Automation Hub repositories
  block:
    - name: Set Hub collection repositories for sync
      ansible.builtin.set_fact:
        hub_collection_repositories: "{{ aap_cac_hub_collection_repositories }}"
      changed_when: false

    - name: Run role infra.aap_configuration.hub_collection_repository_sync
      ansible.builtin.include_role:
        name: infra.aap_configuration.hub_collection_repository_sync
      when: aap_cac_hub_collection_repositories | length > 0
