---
# CaC taskset: Configure Private Automation Hub group roles.
- name: Configure Private Automation Hub group roles
  block:
    - name: Run role infra.aap_configuration.hub_group_roles
      ansible.builtin.include_role:
        name: infra.aap_configuration.hub_group_roles
