---
# CaC taskset: Assign Galaxy Credentials to Gateway Organizations.
- name: Assign Galaxy Credentials to Gateway Organizations
  block:
    - name: Include tasks to create an authentication token
      ansible.builtin.include_tasks:
        file: '{{ role_path }}/tasks/create_authentication_token.yml'
      when: aap_token is not defined
    - name: Run role infra.aap_configuration.dispatch
      ansible.builtin.include_role:
        name: infra.aap_configuration.dispatch
      vars:
        aap_configuration_dispatcher_roles:
          - role: gateway_organizations
            var: aap_organizations
            tags: organizations
            assign_galaxy_credentials_to_org: true
        aap_organizations: '{{ controller_organizations }}'
      tags:
        - organizations
    - name: Include tasks to delete the used authentication token
      ansible.builtin.include_tasks:
        file: '{{ role_path }}/tasks/delete_authentication_token.yml'
      when: aap_token is defined
  vars:
    assign_galaxy_credentials_to_org: true
