---
- name: 'create_authentication_token | Block: Get authentication token'
  when: 'aap_token is not defined'
  block:
    - name: 'create_authentication_token | Get authentication token for the future requests'
      ansible.platform.token:
        gateway_hostname: '{{ aap_cac_gateway_hostname }}'
        gateway_username: '{{ aap_username }}'
        gateway_password: '{{ aap_password }}'
        gateway_validate_certs: '{{ aap_validate_certs }}'
        description: '{{ aap_token_description }}'
        scope: 'write'
        state: 'present'
      register: '__t_token'
