---
galaxy_info:
  description: Validate Keycloak runtime and API health
  company: Lightning IT
  author: Dirk Egert, René Osorio
  license: MIT
  min_ansible_version: '2.18'
  role_name: keycloak_validate
  namespace: default
  galaxy_tags: []
dependencies: []
