---
galaxy_info:
  role_name: checkmk_deploy
  namespace: lit
  author: Lightning IT
  description: Deploy Checkmk monitoring with Podman kube play.
  company: Lightning IT
  license: MIT
  min_ansible_version: "2.18"
  platforms:
    - name: EL
      versions:
        - "9"
  galaxy_tags:
    - modulix
    - kubeplay
    - checkmk
    - monitoring
    - podman

dependencies: []
