---
samba_preflight_strict: true
samba_preflight_check_packages: true
samba_preflight_check_systemd: false
samba_preflight_check_ports: true
samba_preflight_required_ports:
  - "{{ samba_deploy_netbios_port | default(139, true) }}"
  - "{{ samba_deploy_smb_port | default(445, true) }}"
