---
- name: Reconcile Keycloak identity providers  # noqa args[module]
  community.general.keycloak_identity_provider: >-
    {{
      keycloak_cac_provider_definition
      | combine({
          'auth_keycloak_url': keycloak_cac_url,
          'auth_realm': keycloak_cac_realm,
          'auth_username': keycloak_cac_admin_user,
          'auth_password': keycloak_cac_admin_password,
          'validate_certs': keycloak_cac_validate_certs,
          'connection_timeout': keycloak_cac_request_timeout
        })
    }}
  loop: "{{ keycloak_cac_identity_providers }}"
  loop_control:
    loop_var: keycloak_cac_provider_definition
    label: "{{ keycloak_cac_provider_definition.alias }}"
  no_log: true
