---
- name: Converge semaphore cac syntax coverage
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    semaphore_cac_molecule_execute_role: false
  tasks:
    - name: Import lit.supplementary.semaphore_cac for syntax coverage
      ansible.builtin.import_role:
        name: lit.supplementary.semaphore_cac
      when: semaphore_cac_molecule_execute_role | bool

    - name: Record lit.supplementary.semaphore_cac Molecule coverage mode
      ansible.builtin.set_fact:
        semaphore_cac_molecule_coverage_mode: syntax_stub
