FROM docker.io/389ds/dirsrv:3.1@sha256:af99ccf42c1cd02799d674ffdee3612a1bbd426c1a8a636da67ea349659ee5e0

USER root

RUN mkdir -p /opt/wunderbox/bootstrap

COPY bootstrap/seed.ldif /opt/wunderbox/bootstrap/seed.ldif
COPY containerfiles/ldap/entrypoint-wrapper.sh /usr/local/bin/wunderbox-ldap-entrypoint.sh

RUN chmod 0755 /usr/local/bin/wunderbox-ldap-entrypoint.sh

ENTRYPOINT ["/usr/local/bin/wunderbox-ldap-entrypoint.sh"]
