---
- name: Resolve existing Semaphore repository
  ansible.builtin.set_fact:
    semaphore_cac_repository_existing: >-
      {{
        semaphore_cac_repositories_get.json
        | selectattr('name', 'equalto', semaphore_cac_repository.name)
        | list
        | first
        | default({})
      }}
    semaphore_cac_repository_key: >-
      {{
        semaphore_cac_keys_get.json | default([])
        | selectattr('name', 'equalto', semaphore_cac_repository.ssh_key_name | default('None'))
        | list
        | first
        | default({})
      }}
  changed_when: false

- name: Create Semaphore repository
  ansible.builtin.uri:
    url: "{{ semaphore_cac_url }}/api/project/{{ semaphore_cac_project_current.id }}/repositories"
    method: POST
    headers: "{{ semaphore_cac_api_headers }}"
    body_format: json
    body:
      name: "{{ semaphore_cac_repository.name }}"
      project_id: "{{ semaphore_cac_project_current.id }}"
      git_url: "{{ semaphore_cac_repository.git_url }}"
      git_branch: "{{ semaphore_cac_repository.git_branch | default('main') }}"
      ssh_key_id: "{{ semaphore_cac_repository_key.id | default(0) }}"
    validate_certs: "{{ semaphore_cac_validate_certs }}"
    timeout: "{{ semaphore_cac_request_timeout | int }}"
    status_code: 201
  when: semaphore_cac_repository_existing.id is not defined
