---
- name: Get Semaphore project keys
  ansible.builtin.uri:
    url: "{{ semaphore_cac_url }}/api/project/{{ semaphore_cac_project_current.id }}/keys?sort=name&order=asc"
    method: GET
    headers: "{{ semaphore_cac_api_headers }}"
    validate_certs: "{{ semaphore_cac_validate_certs }}"
    timeout: "{{ semaphore_cac_request_timeout | int }}"
    status_code: 200
  register: semaphore_cac_keys_get
  changed_when: false

- name: Ensure Semaphore project keys exist
  ansible.builtin.include_tasks: object_22_key.yml
  loop: "{{ semaphore_cac_project['keys'] | default([]) }}"
  loop_control:
    loop_var: semaphore_cac_key
    label: "{{ semaphore_cac_key.name }}"

- name: Refresh Semaphore project keys
  ansible.builtin.uri:
    url: "{{ semaphore_cac_url }}/api/project/{{ semaphore_cac_project_current.id }}/keys?sort=name&order=asc"
    method: GET
    headers: "{{ semaphore_cac_api_headers }}"
    validate_certs: "{{ semaphore_cac_validate_certs }}"
    timeout: "{{ semaphore_cac_request_timeout | int }}"
    status_code: 200
  register: semaphore_cac_keys_get
  changed_when: false
